# RSS Feeds to monitor
FEEDS = [
"https://www.thv11.com/rss",
"https://talkbusiness.net/feed/",
"https://www.arkansasonline.com/rss/headlines/",
"https://www.kark.com/news/local-news/feed/",
"https://arktimes.com/feed",
"https://www.fox16.com/feed",
"https://katv.com/feed",
"https://governor.arkansas.gov/newsroom/feed/",
"https://humanservices.arkansas.gov/news-feed/feed/",
"https://www.npr.org/rss/rss.php?id=1001",
"https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml",
"https://rss.nytimes.com/services/xml/rss/nyt/National.xml",
"https://rss.nytimes.com/services/xml/rss/nyt/World.xml",
"https://feeds.washingtonpost.com/rss/national",
"https://feeds.washingtonpost.com/rss/world",
"http://rssfeeds.usatoday.com/usatoday-NewsTopStories",
"https://thehill.com/homenews/feed/",
"https://www.politico.com/rss/politicopicks.xml",
"http://feeds.abcnews.com/abcnews/usheadlines",
"http://feeds.abcnews.com/abcnews/internationalheadlines",
"https://www.cbsnews.com/latest/rss/main",
"https://feeds.nbcnews.com/feeds/topstories",
"https://feeds.nbcnews.com/feeds/worldnews",
"https://www.vox.com/rss/index.xml",
"https://nypost.com/feed/",
"https://www.newyorker.com/feed/news",
"https://time.com/newsfeed/feed/",
"https://www.reutersagency.com/feed/",
"https://apnews.com/hub/world-news.rss",
"https://feeds.bbci.co.uk/news/world/rss.xml",
"https://feeds.bbci.co.uk/news/world/us_and_canada/rss.xml",
"https://www.theguardian.com/world/rss",
"https://www.theguardian.com/world/usa/rss",
"https://www.aljazeera.com/xml/rss/all.xml",
"https://www.economist.com/latest/rss.xml",
"https://feeds.bloomberg.com/markets/news.rss",
"http://online.wsj.com/xml/rss/3_7085.xml",
"http://rss.cnn.com/rss/cnn_topstories.rss",
"http://rss.cnn.com/rss/edition_world.rss",
"https://www.govinfo.gov/rss/bills.xml",
"https://www.govinfo.gov/rss/fr.xml",
"http://feeds.arstechnica.com/arstechnica/index/",
"https://www.wired.com/feed/rss",
"https://www.theverge.com/rss/index.xml",
"https://news.ycombinator.com/rss"
]

# Keyword Weights (The "Rule-Based" Model)
KEYWORDS = {
    # High-Consequence Physical Threats
    "grid collapse": 98,
    "black sky event": 98,
    "coordinated attack": 95,
    "physical sabotage": 95,
    "substation attack": 95,
    "ballistic sabotage": 92,
    "transformer fire": 90,
    "targeted assault": 90,
    "grid sabotage": 90,
    "dam failure": 85,
    "water contamination": 85,
    
    # Major Utility Entities & Operators
    "PJM Interconnection": 85,
    "ERCOT": 85,
    "MISO": 85,
    "NextEra Energy": 80,
    "Duke Energy": 80,
    "Southern Company": 80,
    "Dominion Energy": 80,
    "Exelon": 80,
    "American Electric Power": 80,
    "PG&E": 80,
    "National Grid": 80,
    "Iberdrola": 80,
    
    # Generation Facilities & Assets
    "nuclear plant": 88,
    "generation facility": 85,
    "pumping station": 82,
    "natural gas plant": 80,
    "small modular reactor": 80,
    "SMR": 75,
    "hydroelectric dam": 75,
    "peaking plant": 70,
    "transmission tower": 70,
    "substation": 65,
    "solar farm": 60,
    "wind facility": 60,
    
    # Operational & Grid Stability
    "cascading failure": 92,
    "black start": 90,
    "load shedding": 75,
    "rolling blackouts": 75,
    "grid instability": 70,
    "power outage": 65,
    "service disruption": 55,
    "critical infrastructure": 50,
    
    # Security & Site Violation
    "insider threat": 75,
    "security breach": 70,
    "physical breach": 70,
    "unauthorized entry": 65,
    "perimeter violation": 50,
    "copper theft": 40,
    "vandalism": 35,
    
    # Maintenance & Low-Priority
    "equipment failure": 30,
    "hardware fault": 20,
    "planned outage": 10,
    "routine maintenance": 5
}

# Threshold to "Bubble Up" an article
ALERT_THRESHOLD = 45